// Generated by CoffeeScript 1.3.3
(function() {
  var Backbone, Game, GameClient, _;

  Backbone = require('backbone4000');

  Game = require('game/models');

  _ = require('underscore');

  GameClient = exports.GameClient = Backbone.Model.extend4000({
    initialize: function() {
      var _this = this;
      this.subscribe({
        changes: Array
      }, function(msg) {
        return _.map(msg.changes, function(change) {
          return _this.applychange(change);
        });
      });
      return this.subscribe({
        end: true
      }, function(msg) {
        return _.defer(function() {
          return _this.end(msg.end);
        });
      });
    },
    applychange: function(change) {
      var attrs, point, state;
      if (change.a === 'set') {
        attrs = {
          id: change.id
        };
        if (change.o) {
          attrs = _.extend(attrs, change.o);
        }
        point = this.point(change.p);
        point.push(state = new this.state[change.s](attrs));
      }
      if (change.a === 'del') {
        this.byid[change.id].remove();
      }
      if (change.a === 'move') {
        this.byid[change.id].move(this.point(change.p));
      }
      if (change.a === 'msg') {
        return this.byid[change.id].trigger('message', change.m);
      }
    },
    nextid: function(state) {
      return "c" + this.stateid++;
    }
  });

}).call(this);
