// Generated by LiveScript 1.4.0
(function(){
  var window, Backbone, $, validator;
  if (!window) {
    window = {};
  }
  Backbone = require('backbone4000');
  $ = require('jquery');
  validator = require('validator2-extras');
  exports.KeyControler = Backbone.Model.extend4000(validator.ValidatedModel, {
    validator: {
      actions: 'Object'
    },
    send: function(){
      return console.warn("controler trying to send, but no send method is implemented");
    },
    initialize: function(){
      var state, actions, this$ = this;
      state = {};
      actions = this.get('actions');
      $(document).keydown(function(event){
        var key;
        event.preventDefault();
        if (!(key = actions[event.keyCode])) {
          return;
        }
        if (state[key]) {
          return;
        }
        state[key] = true;
        return this$.send({
          ctrl: {
            k: key,
            s: 'd'
          }
        });
      });
      return $(document).keyup(function(event){
        var key;
        event.preventDefault();
        key = event.keyCode;
        if (!(key = actions[event.keyCode])) {
          return;
        }
        if (state[key] == null) {
          return;
        }
        delete state[key];
        return this$.send({
          ctrl: {
            k: key,
            s: 'u'
          }
        });
      });
    },
    end: function(){
      $(document).off('keydown');
      $(document).off('keyup');
      return this.trigger('end');
    }
  });
}).call(this);
