// Generated by CoffeeScript 1.8.0
(function() {
  var $, Backbone, validator, window;

  if (!window) {
    window = {};
  }

  Backbone = require('backbone4000');

  $ = require('jquery-browserify');

  validator = require('validator2-extras');

  exports.KeyControler = Backbone.Model.extend4000(validator.ValidatedModel, {
    validator: {
      actions: 'Object'
    },
    initialize: function() {
      var actions, state;
      state = {};
      actions = this.get('actions');
      $(document).keydown((function(_this) {
        return function(event) {
          var key;
          console.log(event.keyCode);
          if (!(key = actions[event.keyCode])) {
            return;
          }
          if (state[key]) {
            return;
          }
          state[key] = true;
          return _this.send({
            ctrl: {
              k: key,
              s: 'd'
            }
          });
        };
      })(this));
      return $(document).keyup((function(_this) {
        return function(event) {
          var key;
          key = event.keyCode;
          if (!(key = actions[event.keyCode])) {
            return;
          }
          if (state[key] == null) {
            return;
          }
          delete state[key];
          return _this.send({
            ctrl: {
              k: key,
              s: 'u'
            }
          });
        };
      })(this));
    },
    send: function() {
      return console.warn("controler trying to send, but no send method is implemented");
    },
    end: function() {
      $(document).off('keydown');
      $(document).off('keyup');
      return this.trigger('end');
    }
  });

}).call(this);
