// Generated by CoffeeScript 1.7.1
(function() {
  var Backbone, v, validator, views, _;

  _ = require('underscore');

  Backbone = require('backbone4000');

  validator = require('validator2-extras');

  v = validator.v;

  views = require('./views');

  exports.Sounds = validator.ValidatedModel.extend4000({});

}).call(this);
